/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSgpaRouteImport } from './routes/app.sgpa'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppImprovementRouteImport } from './routes/app.improvement'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCgpaRouteImport } from './routes/app.cgpa'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSgpaRoute = AppSgpaRouteImport.update({
  id: '/sgpa',
  path: '/sgpa',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppImprovementRoute = AppImprovementRouteImport.update({
  id: '/improvement',
  path: '/improvement',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCgpaRoute = AppCgpaRouteImport.update({
  id: '/cgpa',
  path: '/cgpa',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/cgpa': typeof AppCgpaRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/improvement': typeof AppImprovementRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sgpa': typeof AppSgpaRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/cgpa': typeof AppCgpaRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/improvement': typeof AppImprovementRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sgpa': typeof AppSgpaRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/cgpa': typeof AppCgpaRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/improvement': typeof AppImprovementRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sgpa': typeof AppSgpaRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/attendance'
    | '/app/cgpa'
    | '/app/dashboard'
    | '/app/improvement'
    | '/app/settings'
    | '/app/sgpa'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app/attendance'
    | '/app/cgpa'
    | '/app/dashboard'
    | '/app/improvement'
    | '/app/settings'
    | '/app/sgpa'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/attendance'
    | '/app/cgpa'
    | '/app/dashboard'
    | '/app/improvement'
    | '/app/settings'
    | '/app/sgpa'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sgpa': {
      id: '/app/sgpa'
      path: '/sgpa'
      fullPath: '/app/sgpa'
      preLoaderRoute: typeof AppSgpaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/improvement': {
      id: '/app/improvement'
      path: '/improvement'
      fullPath: '/app/improvement'
      preLoaderRoute: typeof AppImprovementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cgpa': {
      id: '/app/cgpa'
      path: '/cgpa'
      fullPath: '/app/cgpa'
      preLoaderRoute: typeof AppCgpaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppCgpaRoute: typeof AppCgpaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppImprovementRoute: typeof AppImprovementRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSgpaRoute: typeof AppSgpaRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppCgpaRoute: AppCgpaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppImprovementRoute: AppImprovementRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSgpaRoute: AppSgpaRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
